"""Initial Migration

Revision ID: bcfd6d317ed2
Revises: 
Create Date: 2023-10-07 20:50:01.580885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfd6d317ed2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preceptor')
    op.drop_table('profesor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profesor',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__profesor__3213E83F9B5C996D')
    )
    op.create_table('preceptor',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__precepto__3213E83FF013EF78')
    )
    # ### end Alembic commands ###
